// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBMnqo2j5JvGjB4QHsVPjyxGpQUElQdE',
    appId: '1:922542347086:web:0cf5c490f8e1a5299a441f',
    messagingSenderId: '922542347086',
    projectId: 'thakafah-reports',
    authDomain: 'thakafah-reports.firebaseapp.com',
    storageBucket: 'thakafah-reports.appspot.com',
    measurementId: 'G-BV7XQVHTM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGMt2OaDbQlpnz935FEWzc-yESMZ7WQY',
    appId: '1:922542347086:android:0d16e1866965f0f09a441f',
    messagingSenderId: '922542347086',
    projectId: 'thakafah-reports',
    storageBucket: 'thakafah-reports.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjdp_GefAwHYnDcINd7d2QDyJ_F6Z7PA',
    appId: '1:922542347086:ios:de19354a8c01df1c9a441f',
    messagingSenderId: '922542347086',
    projectId: 'thakafah-reports',
    storageBucket: 'thakafah-reports.appspot.com',
    iosBundleId: 'com.thakafah.report.thakafahReports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvjdp_GefAwHYnDcINd7d2QDyJ_F6Z7PA',
    appId: '1:922542347086:ios:d76b8ded8fd2b53c9a441f',
    messagingSenderId: '922542347086',
    projectId: 'thakafah-reports',
    storageBucket: 'thakafah-reports.appspot.com',
    iosBundleId: 'com.thakafah.report.thakafahReports.RunnerTests',
  );
}
