// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbtc8UxjR83RjrYJhn4PEJlT6QXl4xbTc',
    appId: '1:948177886168:web:ef739beef737f6ba70f0ad',
    messagingSenderId: '948177886168',
    projectId: 'thakafah',
    authDomain: 'thakafah.firebaseapp.com',
    storageBucket: 'thakafah.appspot.com',
    measurementId: 'G-5J0MT1MTDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0W6HleUwNW8G7UBKLXRg4YSMEOiZjVI',
    appId: '1:948177886168:android:68083486f6beb68f70f0ad',
    messagingSenderId: '948177886168',
    projectId: 'thakafah',
    storageBucket: 'thakafah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmG8ScDiIz6Ux8KQAdQFFosLfvVm_1L8',
    appId: '1:948177886168:ios:5020382e21b141ac70f0ad',
    messagingSenderId: '948177886168',
    projectId: 'thakafah',
    storageBucket: 'thakafah.appspot.com',
    androidClientId: '948177886168-bb4cns1hr5idcd6jn8mf34aa4kmkuosm.apps.googleusercontent.com',
    iosBundleId: 'com.thakafah.report.thakafahReports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPmG8ScDiIz6Ux8KQAdQFFosLfvVm_1L8',
    appId: '1:948177886168:ios:3da310a1d72f7ed670f0ad',
    messagingSenderId: '948177886168',
    projectId: 'thakafah',
    storageBucket: 'thakafah.appspot.com',
    androidClientId: '948177886168-bb4cns1hr5idcd6jn8mf34aa4kmkuosm.apps.googleusercontent.com',
    iosBundleId: 'com.thakafah.report.thakafahReports.RunnerTests',
  );
}
